import Head from "next/head";
import { FC } from "react";
import { Navbar } from "../Navbar/Navbar";
import styles from "./MainLayout.module.css";
interface Props {
  children: any;
}
export const MainLayout: FC<Props> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className={styles.main}>{children}</main>
    </>
  );
};
